// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIskd9ic2f5XB8KKcZzPwTeGi0TaOoy0',
    appId: '1:599502589313:web:df48a816e596ef070e6c80',
    messagingSenderId: '599502589313',
    projectId: 'cashmate-a0e27',
    authDomain: 'cashmate-a0e27.firebaseapp.com',
    storageBucket: 'cashmate-a0e27.appspot.com',
    measurementId: 'G-PFHN6DKBKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJBqrJ4Qc15ntxh3ii_t2yhgodneyPIA0',
    appId: '1:599502589313:android:2ede1b34689a9d350e6c80',
    messagingSenderId: '599502589313',
    projectId: 'cashmate-a0e27',
    storageBucket: 'cashmate-a0e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxri4Ix313hjosFfuA4jD5Ub9U9QvPmjE',
    appId: '1:599502589313:ios:06ac6ba51a87dd530e6c80',
    messagingSenderId: '599502589313',
    projectId: 'cashmate-a0e27',
    storageBucket: 'cashmate-a0e27.appspot.com',
    iosBundleId: 'com.example.cashmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxri4Ix313hjosFfuA4jD5Ub9U9QvPmjE',
    appId: '1:599502589313:ios:2b9bb1879ab222690e6c80',
    messagingSenderId: '599502589313',
    projectId: 'cashmate-a0e27',
    storageBucket: 'cashmate-a0e27.appspot.com',
    iosBundleId: 'com.example.cashmate.RunnerTests',
  );
}
